attacks_config = {
    'SQLInjection': False,
    'SensitiveInformationDisclosure': True,
    'ReflectedXSS': True,
    'StoredXSS': False,
    'InsufficientSessionInvalidation': False,
    'SensitiveDatawithinCookie': False,  #If 'True' set 'ForcedBrowsing' to 'None'
    'ForcedBrowsing': None,
    'HardCodedKey': True,
    'DebugModeON': True,
    'PathTraversal': True,
    'OSCommandInjection': True,
    'CookiesWithoutSecurityAttributes' : True,
    'Clickjacking' : True,
    'InsufficientLogging':True,
    'InsertionOfSensitiveInformationIntoLogFile' : True,
    'WeakPasswordRequirements' : False,
    'IDOR': True,
    'CSRF': False,
    'VulnerablePostgreSQL' : False,
    'SSRF' : False,
}