services:
  apache:
    build:
      context: .
      dockerfile: apache/Docker/Dockerfile-apache
    #UnprotectedTransportofCredentials-1 - START
    #Fix
    ports:
      - 8081:80
      - 8080:443
    #UnprotectedTransportofCredentials-1 - END
    networks:
      - coffee-shop
    restart:
      always

  postgresql:
    #VulnerablePostgreSQL-1 - START
    #Fix
    image: postgres
    #VulnerablePostgreSQL-1 - END
    networks:
      - coffee-shop
    ports:
      - 5433:5432
    restart:
      always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - coffee-shop
    ports:
      - 81:80
    restart:
      always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  coffee-shop:
volumes:
  postgresql-data:
    driver: local
