services:
  apache:
    build:
      context: .
      dockerfile: apache/Docker/Dockerfile-apache
    environment:
      - FLASK_DEBUG=True
    #UnprotectedTransportofCredentials-1 - START
    #Fix
    ports:
      - 9090:443
    #UnprotectedTransportofCredentials-1 - END
    networks:
      - coffee-shop
    restart:
      always

  #FunctionalityFromUntrustedSource-1 - START
  #Vulnerability
  apache-js:
      image: httpd:alpine
      ports:
        - "9091:80"
      volumes:
        - ./src/static/js/:/usr/local/apache2/htdocs
        - ./apache/Docker/apache-js.conf:/usr/local/apache2/conf/apache-js.conf
      networks:
        - coffee-shop
      restart: always
  #FunctionalityFromUntrustedSource-1 - END
  
  postgresql:
    #VulnerablePostgreSQL-1 - START
    #Fix
    image: postgres
    #VulnerablePostgreSQL-1 - END
    networks:
      - coffee-shop
    ports:
      - 5433:5432
    restart:
      always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

networks:
  coffee-shop:
volumes:
  postgresql-data:
    driver: local
