#UnprotectedTransportofCredentials-1 - START
<VirtualHost *:443>
    ServerName 127.0.0.1

    WSGIDaemonProcess Coffee-Shop user=www-data group=www-data threads=5
    WSGIScriptAlias / /var/www/html/Coffee-Shop/app.wsgi

    SSLEngine on
    SSLCertificateFile      /etc/apache2/ssl/server.crt
    SSLCertificateKeyFile /etc/apache2/ssl/server.key

    # CustomErrorPages-1 - START
    #Vulnerability
    #No custom error pages.
    # CustomErrorPages-1 - END

    <Directory /var/www/html/Coffee-Shop>
        WSGIProcessGroup Coffee-Shop
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
        #CustomErrorPages-3 - START
        #Vulnerability
        WSGIErrorOverride On
        #CustomErrorPages-3 - END
        #DebugModeON-4 - START
        #DebugModeON-4 - END
    </Directory>

    # DirectoryListing-1 - START
    #Vulnerability
    Alias /listing /var/www/html/Coffee-Shop
    <Directory /var/www/html/Coffee-Shop>
        Options +Indexes
    </Directory>
    # DirectoryListing-1 - END
</VirtualHost>
#UnprotectedTransportofCredentials-1 - END