#UnprotectedTransportofCredentials-1 - START
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/
    #DirectoryListing-1 - START
    #Vulnerability
    <Directory /var/www/html/Coffee-Shop/>
        Options Indexes FollowSymLinks MultiViews
        Order allow,deny
        Allow from All
    </Directory>
    #DirectoryListing-1 - END
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    ProxyPass /app http://127.0.0.1:5000/
    ProxyPassReverse /app http://127.0.0.1:5000/
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin webmaster@localhost
    ServerName localhost
    DocumentRoot /var/www/html/
    #DirectoryListing-1 - START
    #Vulnerability
    <Directory /var/www/html/Coffee-Shop/>
        Options Indexes FollowSymLinks MultiViews
        Order allow,deny
        Allow from All
    </Directory>
    #DirectoryListing-1 - END
    ErrorLog ${APACHE_LOG_DIR}/error-ssl.log
    CustomLog ${APACHE_LOG_DIR}/access-ssl.log combined
                
    SSLEngine on
    SSLCertificateFile      /etc/apache2/ssl/server.crt
    SSLCertificateKeyFile /etc/apache2/ssl/server.key

    ProxyPass /app http://127.0.0.1:5000/
    ProxyPassReverse /app http://127.0.0.1:5000/
</VirtualHost>
#UnprotectedTransportofCredentials-1 - END
