#UnprotectedTransportofCredentials-1 - START
<VirtualHost *:443>
    ServerAdmin webmaster@localhost
    ServerName 127.0.0.1
    DocumentRoot /var/www/html/

    # DirectoryListing-1 - START
    #Fix
    <Directory /var/www/html/Coffee-Shop/>
        Options FollowSymLinks MultiViews
        Order allow,deny
        Allow from All
    </Directory>
    # DirectoryListing-1 - END

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLEngine on
    SSLCertificateFile      /etc/apache2/ssl/server.crt
    SSLCertificateKeyFile /etc/apache2/ssl/server.key

    # CustomErrorPages-1 - START
    #Fix
    ErrorDocument 403 /403.html
    ErrorDocument 404 /404.html
    ErrorDocument 500 /50x.html
    ErrorDocument 502 /50x.html
    ErrorDocument 503 /50x.html
    ErrorDocument 504 /50x.html
    # CustomErrorPages-1 - END

    # Mod_rewrite rules for URL structure
    RewriteEngine On

    # Redirect root URL to /app
    RewriteRule ^/$ /app [R=307,L]

    # Exclude this from rewriting
    RewriteCond %{REQUEST_URI} !^/Coffee-Shop
    RewriteCond %{REQUEST_URI} !^/icons/
    RewriteCond %{REQUEST_URI} !^/app
    RewriteCond %{REQUEST_URI} !^/403.html
    RewriteCond %{REQUEST_URI} !^/404.html
    RewriteCond %{REQUEST_URI} !^/50x.html
    RewriteRule ^(.*)$ /app$1 [R=307,L]

    # Proxy configuration
    <Location "/app">
        ProxyPass http://127.0.0.1:5000/
        ProxyPassReverse http://127.0.0.1:5000/
        ProxyErrorOverride On
    </Location>
</VirtualHost>





#UnprotectedTransportofCredentials-1 - END