FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y apache2 apache2-utils apache2-dev sudo python3 python3-pip php8.1 php8.1-cli php-cgi libapache2-mod-php8.1 -y \
    && a2enmod proxy proxy_http autoindex headers ssl rewrite php8.1

COPY . /var/www/html/Coffee-Shop
RUN chown -R  www-data:root /var/www/html/Coffee-Shop
RUN echo "ALL ALL=(ALL) NOPASSWD: /bin/cat" > /etc/sudoers.d/nopassword
RUN echo 'root:root' | chpasswd -m
WORKDIR /var/www/html/Coffee-Shop
COPY src/templates/custom_errors/ /var/www/html/
COPY ssl /etc/apache2/ssl
RUN cat apache/Docker/coffee-shop.conf > /etc/apache2/sites-available/000-default.conf

RUN apt-get -y install postgresql-client
RUN apt-get -y install libapache2-mod-wsgi-py3
RUN pip install -r requirements.txt

CMD ["bash", "-c", "python3 app.py & apachectl -D FOREGROUND"]
