FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y apache2 apache2-utils apache2-dev python3 python3-pip \
    && a2enmod proxy proxy_http autoindex headers ssl \
    && a2enmod ssl \
    && a2enmod rewrite

COPY . /var/www/html/Coffee-Shop

RUN chmod -R 777 /var/www/html/Coffee-Shop
WORKDIR /var/www/html/Coffee-Shop
COPY ssl /etc/apache2/ssl
RUN cat apache/Docker/coffee-shop.conf > /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite


RUN pip install -r requirements.txt
RUN pip uninstall Werkzeug -y
RUN pip install Werkzeug==2.3.7


CMD ["bash", "-c", "python3 app.py & apachectl -D FOREGROUND"]